server:
  port: 80
#eureka集群
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-consumer-feign-order
# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
#ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间，设置等待5000为5秒时间
  #ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  #ConnectTimeout: 5000
feign:
  client:
    config:
      default:
        # 日志级别
        loggerLevel: full
        # 超时设置 1.5 秒超时
        connectTimeout: 5000
        readTimeout: 8000
  # 断路器
  circuitbreaker:
    enabled: true
