server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  client:
    config:
      default:
        # 日志级别
        loggerLevel: full
        # 超时设置 5 秒超时
        connectTimeout: 5000
        readTimeout: 5000

  # 断路器
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true
#此时才是真的超时时间为5秒，上面的readTimeout好像不生效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
