server:
  port: 81
spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进eureka  默认为true
    fetch-registry: true  #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    service-url:
      #单机配置
      defaultZone: http://localhost:7001/eureka