server:
  port: 8004
spring:
  application:
    name: cloud-providerconsul-payment
  cloud:
    consul:
      host: localhost
      prot: 8500
      discovery:
        service-name: ${spring.application.name}
